// Code generated by "stringer -type=ColorMode -linecomment"; DO NOT EDIT.

package clog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorAuto-0]
	_ = x[ColorAlways-1]
	_ = x[ColorNever-2]
}

const _ColorMode_name = "autoalwaysnever"

var _ColorMode_index = [...]uint8{0, 4, 10, 15}

func (i ColorMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ColorMode_index)-1 {
		return "ColorMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorMode_name[_ColorMode_index[idx]:_ColorMode_index[idx+1]]
}
