// Code generated by internal/gen/fieldmethods; DO NOT EDIT.

package clog

// Column adds a file path field with a line and column number as a clickable terminal hyperlink.
// Respects the logger's [ColorMode] setting.
func (c *Context) Column(key, path string, line, column int) *Context {
	if line < 1 {
		line = 1
	}

	if column < 1 {
		column = 1
	}

	c.Fields = append(
		c.Fields,
		Field{Key: key, Value: c.logger.Output().pathLink(path, line, column)},
	)
	return c
}

// Columns adds a string slice field where each element is a path:line:column
// hyperlink. Respects the logger's [ColorMode] setting.
func (c *Context) Columns(key string, items []Column) *Context {
	output := c.logger.Output()
	vals := make([]string, len(items))
	for i, item := range items {
		line, column := item.Line, item.Column
		if line < 1 {
			line = 1
		}
		if column < 1 {
			column = 1
		}
		vals[i] = output.pathLink(item.Path, line, column)
	}
	c.Fields = append(c.Fields, Field{Key: key, Value: vals})
	return c
}

// Dict adds a group of fields under a key prefix using dot notation.
// Build the nested fields using [Dict] to create a field-only Event:
//
//	logger := clog.With().Dict("db", clog.Dict().
//	    Str("host", "localhost").
//	    Int("port", 5432),
//	).Logger()
func (c *Context) Dict(key string, dict *Event) *Context {
	if dict == nil {
		return c
	}

	for _, f := range dict.fields {
		c.Fields = append(c.Fields, Field{Key: key + "." + f.Key, Value: f.Value})
	}
	return c
}

// Line adds a file path field with a line number as a clickable terminal hyperlink.
// Respects the logger's [ColorMode] setting. If line < 1, the line number is
// omitted and the field is rendered as a plain path hyperlink (equivalent to
// [Context.Path]).
func (c *Context) Line(key, path string, line int) *Context {
	if line < 1 {
		return c.Path(key, path)
	}

	c.Fields = append(
		c.Fields,
		Field{Key: key, Value: c.logger.Output().pathLink(path, line, 0)},
	)
	return c
}

// Lines adds a string slice field where each element is a path:line
// hyperlink. If an item's Line < 1, that element is rendered as a plain path
// hyperlink (equivalent to [Context.Path]). Respects the logger's [ColorMode]
// setting.
func (c *Context) Lines(key string, items []Line) *Context {
	output := c.logger.Output()
	vals := make([]string, len(items))
	for i, item := range items {
		vals[i] = output.pathLink(item.Path, item.Line, 0)
	}
	c.Fields = append(c.Fields, Field{Key: key, Value: vals})
	return c
}

// Link adds a field as a clickable terminal hyperlink with custom URL and display text.
// Respects the logger's [ColorMode] setting.
func (c *Context) Link(key, url, text string) *Context {
	c.Fields = append(
		c.Fields,
		Field{Key: key, Value: c.logger.Output().hyperlink(url, text)},
	)
	return c
}

// Links adds a string slice field where each element is a hyperlink.
func (c *Context) Links(key string, links []Link) *Context {
	output := c.logger.Output()
	vals := make([]string, len(links))
	for i, l := range links {
		vals[i] = output.hyperlink(l.URL, l.Text)
	}
	c.Fields = append(c.Fields, Field{Key: key, Value: vals})
	return c
}

// Path adds a file path field as a clickable terminal hyperlink.
// Respects the logger's [ColorMode] setting.
func (c *Context) Path(key, path string) *Context {
	c.Fields = append(
		c.Fields,
		Field{Key: key, Value: c.logger.Output().pathLink(path, 0, 0)},
	)
	return c
}

// Paths adds a string slice field where each element is a path hyperlink.
// Respects the logger's [ColorMode] setting.
func (c *Context) Paths(key string, paths []string) *Context {
	output := c.logger.Output()
	vals := make([]string, len(paths))
	for i, p := range paths {
		vals[i] = output.pathLink(p, 0, 0)
	}
	c.Fields = append(c.Fields, Field{Key: key, Value: vals})
	return c
}

// PathText adds a file path field as a clickable terminal hyperlink whose
// visible label is text rather than path. The link still targets path, so a
// caller can show an abbreviated or home-contracted path (e.g. ~/bin/foo)
// while linking to its full location. Respects the logger's [ColorMode]
// setting.
func (c *Context) PathText(key, text, path string) *Context {
	c.Fields = append(
		c.Fields,
		Field{Key: key, Value: c.logger.Output().pathLinkText(text, path, 0, 0)},
	)
	return c
}

// URL adds a field as a clickable terminal hyperlink where the URL is also the display text.
// Respects the logger's [ColorMode] setting.
func (c *Context) URL(key, url string) *Context {
	c.Fields = append(
		c.Fields,
		Field{Key: key, Value: c.logger.Output().hyperlink(url, url)},
	)
	return c
}

// URLs adds a string slice field where each element is a hyperlink
// with the URL as the display text.
func (c *Context) URLs(key string, urls []string) *Context {
	output := c.logger.Output()
	vals := make([]string, len(urls))
	for i, u := range urls {
		vals[i] = output.hyperlink(u, u)
	}
	c.Fields = append(c.Fields, Field{Key: key, Value: vals})
	return c
}
