// Code generated by internal/gen/fieldmethods; DO NOT EDIT.

package clog

import (
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"

	"github.com/gechr/clog/internal/core"
)

// Any adds a field with an arbitrary value.
func (e *Event) Any(key string, val any) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Anys adds a slice of arbitrary values. Individual elements are
// highlighted using reflection to determine their type.
func (e *Event) Anys(key string, vals []any) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Base64 adds a []byte field encoded as a base64 string.
func (e *Event) Base64(key string, val []byte) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: base64.StdEncoding.EncodeToString(val)})
	return e
}

// Bool adds a bool field.
func (e *Event) Bool(key string, val bool) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Bools adds a bool slice field.
func (e *Event) Bools(key string, vals []bool) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Bytes adds a []byte field. If val is valid JSON it is stored as [RawJSON]
// with syntax highlighting; otherwise it is stored as a plain string.
func (e *Event) Bytes(key string, val []byte) *Event {
	if e == nil {
		return e
	}

	if json.Valid(val) {
		e.fields = append(e.fields, Field{Key: key, Value: core.RawJSON(val)})
	} else {
		e.fields = append(e.fields, Field{Key: key, Value: string(val)})
	}
	return e
}

// Durations adds a [time.Duration] slice field.
func (e *Event) Durations(key string, vals []time.Duration) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// AnErr adds an error as a keyed field. No-op if err is nil.
// Unlike [Event.Err], this does not interact with [Event.Send] or [Event.Msg]
// semantics - the error is simply added as a regular field with the given key.
func (e *Event) AnErr(key string, err error) *Event {
	if e == nil {
		return e
	}

	if err == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: err})
	return e
}

// Errs adds an error slice field. Each error is converted to its message
// string; nil errors are rendered as [Nil] ("<nil>").
func (e *Event) Errs(key string, vals []error) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: core.ErrSliceToStrings(vals)})
	return e
}

// Float32 adds a float32 field.
func (e *Event) Float32(key string, val float32) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Float64 adds a float64 field.
func (e *Event) Float64(key string, val float64) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Floats32 adds a float32 slice field.
func (e *Event) Floats32(key string, vals []float32) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Floats64 adds a float64 slice field.
func (e *Event) Floats64(key string, vals []float64) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Hex adds a []byte field encoded as a hex string.
func (e *Event) Hex(key string, val []byte) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: hex.EncodeToString(val)})
	return e
}

// Int adds an int field.
func (e *Event) Int(key string, val int) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Int8 adds an int8 field.
func (e *Event) Int8(key string, val int8) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Int16 adds an int16 field.
func (e *Event) Int16(key string, val int16) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Int32 adds an int32 field.
func (e *Event) Int32(key string, val int32) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Int64 adds an int64 field.
func (e *Event) Int64(key string, val int64) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Ints adds an int slice field.
func (e *Event) Ints(key string, vals []int) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Ints8 adds an int8 slice field.
func (e *Event) Ints8(key string, vals []int8) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Ints16 adds an int16 slice field.
func (e *Event) Ints16(key string, vals []int16) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Ints32 adds an int32 slice field.
func (e *Event) Ints32(key string, vals []int32) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Ints64 adds an int64 slice field.
func (e *Event) Ints64(key string, vals []int64) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// JSON marshals val to JSON and adds it as a highlighted field.
// On marshal error the field value is the error string.
func (e *Event) JSON(key string, val any) *Event {
	if e == nil {
		return e
	}

	b, err := json.Marshal(val)
	if err != nil {
		e.fields = append(e.fields, Field{Key: key, Value: err.Error()})
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: core.RawJSON(b)})
	return e
}

// Quantities adds a quantity string slice field. Each element is styled
// with the [style.Config.FieldQuantity] segment styles.
func (e *Event) Quantities(key string, vals []string) *Event {
	if e == nil {
		return e
	}

	q := make([]core.QuantityField, len(vals))
	for i, v := range vals {
		q[i] = core.QuantityField(v)
	}
	e.fields = append(e.fields, Field{Key: key, Value: q})
	return e
}

// Quantity adds a quantity string field where numeric and unit segments are
// styled independently (e.g. "5m", "5.1km", "100MB").
// The value is styled with the [style.Config.FieldQuantity] segment styles.
func (e *Event) Quantity(key, val string) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: core.QuantityField(val)})
	return e
}

// RawJSON adds a field with pre-serialized JSON bytes, emitted verbatim
// without quoting or escaping. The bytes must be valid JSON.
func (e *Event) RawJSON(key string, val []byte) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: core.RawJSON(val)})
	return e
}

// Str adds a string field.
func (e *Event) Str(key, val string) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Stringer adds a field by calling the value's String method. No-op if val is nil.
func (e *Event) Stringer(key string, val fmt.Stringer) *Event {
	if e == nil {
		return e
	}

	if core.IsNilStringer(val) {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val.String()})
	return e
}

// Stringers adds a field with a slice of [fmt.Stringer] values.
func (e *Event) Stringers(key string, vals []fmt.Stringer) *Event {
	if e == nil {
		return e
	}

	strs := make([]string, len(vals))
	for i, v := range vals {
		if core.IsNilStringer(v) {
			strs[i] = Nil
		} else {
			strs[i] = v.String()
		}
	}
	e.fields = append(e.fields, Field{Key: key, Value: strs})
	return e
}

// Strs adds a string slice field.
func (e *Event) Strs(key string, vals []string) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Time adds a [time.Time] field.
func (e *Event) Time(key string, val time.Time) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Times adds a [time.Time] slice field.
func (e *Event) Times(key string, vals []time.Time) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// TimeDiff adds the field key with the duration between t and start.
// If t is not after start, the duration is zero.
func (e *Event) TimeDiff(key string, t, start time.Time) *Event {
	if e == nil {
		return e
	}

	var d time.Duration
	if t.After(start) {
		d = t.Sub(start)
	}
	e.fields = append(e.fields, Field{Key: key, Value: d})
	return e
}

// Uint adds a uint field.
func (e *Event) Uint(key string, val uint) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Uint8 adds a uint8 field.
func (e *Event) Uint8(key string, val uint8) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Uint16 adds a uint16 field.
func (e *Event) Uint16(key string, val uint16) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Uint32 adds a uint32 field.
func (e *Event) Uint32(key string, val uint32) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Uint64 adds a uint64 field.
func (e *Event) Uint64(key string, val uint64) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: val})
	return e
}

// Uints adds a uint slice field.
func (e *Event) Uints(key string, vals []uint) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Uints8 adds a uint8 slice field.
func (e *Event) Uints8(key string, vals []uint8) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Uints16 adds a uint16 slice field.
func (e *Event) Uints16(key string, vals []uint16) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Uints32 adds a uint32 slice field.
func (e *Event) Uints32(key string, vals []uint32) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}

// Uints64 adds a uint64 slice field.
func (e *Event) Uints64(key string, vals []uint64) *Event {
	if e == nil {
		return e
	}

	e.fields = append(e.fields, Field{Key: key, Value: vals})
	return e
}
