// Code generated by "stringer -type=Fallback -linecomment"; DO NOT EDIT.

package hyperlink

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FallbackURL-0]
	_ = x[FallbackExpanded-1]
	_ = x[FallbackMarkdown-2]
	_ = x[FallbackText-3]
}

const _Fallback_name = "urlexpandedmarkdowntext"

var _Fallback_index = [...]uint8{0, 3, 11, 19, 23}

func (i Fallback) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Fallback_index)-1 {
		return "Fallback(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Fallback_name[_Fallback_index[idx]:_Fallback_index[idx+1]]
}
