// Code generated by internal/gen/fieldmethods; DO NOT EDIT.

package core

import (
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"
)

// Any adds a field with an arbitrary value.
func (fb *FieldBuilder[T]) Any(key string, val any) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Anys adds a slice of arbitrary values.
func (fb *FieldBuilder[T]) Anys(key string, vals []any) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Base64 adds a []byte field encoded as a base64 string.
func (fb *FieldBuilder[T]) Base64(key string, val []byte) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: base64.StdEncoding.EncodeToString(val)})
	return fb.Self
}

// Bool adds a bool field.
func (fb *FieldBuilder[T]) Bool(key string, val bool) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Bools adds a bool slice field.
func (fb *FieldBuilder[T]) Bools(key string, vals []bool) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Bytes adds a []byte field. If val is valid JSON it is stored as [RawJSON]
// with syntax highlighting; otherwise it is stored as a plain string.
func (fb *FieldBuilder[T]) Bytes(key string, val []byte) *T {
	if json.Valid(val) {
		fb.Fields = append(fb.Fields, Field{Key: key, Value: RawJSON(val)})
	} else {
		fb.Fields = append(fb.Fields, Field{Key: key, Value: string(val)})
	}
	return fb.Self
}

// Durations adds a [time.Duration] slice field.
func (fb *FieldBuilder[T]) Durations(key string, vals []time.Duration) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// AnErr adds an error as a keyed field. No-op if err is nil.
func (fb *FieldBuilder[T]) AnErr(key string, err error) *T {
	if err == nil {
		return fb.Self
	}

	fb.Fields = append(fb.Fields, Field{Key: key, Value: err})
	return fb.Self
}

// Errs adds an error slice field. Each error is converted to its message
// string; nil errors are rendered as Nil ("<nil>").
func (fb *FieldBuilder[T]) Errs(key string, vals []error) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: ErrSliceToStrings(vals)})
	return fb.Self
}

// Float32 adds a float32 field.
func (fb *FieldBuilder[T]) Float32(key string, val float32) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Float64 adds a float64 field.
func (fb *FieldBuilder[T]) Float64(key string, val float64) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Floats32 adds a float32 slice field.
func (fb *FieldBuilder[T]) Floats32(key string, vals []float32) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Floats64 adds a float64 slice field.
func (fb *FieldBuilder[T]) Floats64(key string, vals []float64) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Hex adds a []byte field encoded as a hex string.
func (fb *FieldBuilder[T]) Hex(key string, val []byte) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: hex.EncodeToString(val)})
	return fb.Self
}

// Int adds an int field.
func (fb *FieldBuilder[T]) Int(key string, val int) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Int8 adds an int8 field.
func (fb *FieldBuilder[T]) Int8(key string, val int8) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Int16 adds an int16 field.
func (fb *FieldBuilder[T]) Int16(key string, val int16) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Int32 adds an int32 field.
func (fb *FieldBuilder[T]) Int32(key string, val int32) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Int64 adds an int64 field.
func (fb *FieldBuilder[T]) Int64(key string, val int64) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Ints adds an int slice field.
func (fb *FieldBuilder[T]) Ints(key string, vals []int) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Ints8 adds an int8 slice field.
func (fb *FieldBuilder[T]) Ints8(key string, vals []int8) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Ints16 adds an int16 slice field.
func (fb *FieldBuilder[T]) Ints16(key string, vals []int16) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Ints32 adds an int32 slice field.
func (fb *FieldBuilder[T]) Ints32(key string, vals []int32) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Ints64 adds an int64 slice field.
func (fb *FieldBuilder[T]) Ints64(key string, vals []int64) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// JSON marshals val to JSON and adds it as a highlighted field.
// On marshal error the field value is the error string.
func (fb *FieldBuilder[T]) JSON(key string, val any) *T {
	b, err := json.Marshal(val)
	if err != nil {
		fb.Fields = append(fb.Fields, Field{Key: key, Value: err.Error()})
		return fb.Self
	}

	fb.Fields = append(fb.Fields, Field{Key: key, Value: RawJSON(b)})
	return fb.Self
}

// Quantities adds a quantity string slice field.
func (fb *FieldBuilder[T]) Quantities(key string, vals []string) *T {
	q := make([]QuantityField, len(vals))
	for i, v := range vals {
		q[i] = QuantityField(v)
	}
	fb.Fields = append(fb.Fields, Field{Key: key, Value: q})
	return fb.Self
}

// Quantity adds a quantity string field where numeric and unit segments are
// styled independently (e.g. "5m", "5.1km", "100MB").
func (fb *FieldBuilder[T]) Quantity(key, val string) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: QuantityField(val)})
	return fb.Self
}

// RawJSON adds a field with pre-serialized JSON bytes, emitted verbatim
// without quoting or escaping.
func (fb *FieldBuilder[T]) RawJSON(key string, val []byte) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: RawJSON(val)})
	return fb.Self
}

// Str adds a string field.
func (fb *FieldBuilder[T]) Str(key, val string) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Stringer adds a field by calling the value's String method. No-op if val is nil.
func (fb *FieldBuilder[T]) Stringer(key string, val fmt.Stringer) *T {
	if IsNilStringer(val) {
		return fb.Self
	}

	fb.Fields = append(fb.Fields, Field{Key: key, Value: val.String()})
	return fb.Self
}

// Stringers adds a field with a slice of [fmt.Stringer] values.
func (fb *FieldBuilder[T]) Stringers(key string, vals []fmt.Stringer) *T {
	strs := make([]string, len(vals))
	for i, v := range vals {
		if IsNilStringer(v) {
			strs[i] = Nil
		} else {
			strs[i] = v.String()
		}
	}
	fb.Fields = append(fb.Fields, Field{Key: key, Value: strs})
	return fb.Self
}

// Strs adds a string slice field.
func (fb *FieldBuilder[T]) Strs(key string, vals []string) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Time adds a [time.Time] field.
func (fb *FieldBuilder[T]) Time(key string, val time.Time) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Times adds a [time.Time] slice field.
func (fb *FieldBuilder[T]) Times(key string, vals []time.Time) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// TimeDiff adds the field key with the duration between t and start.
// If t is not after start, the duration is zero.
func (fb *FieldBuilder[T]) TimeDiff(key string, t, start time.Time) *T {
	var d time.Duration
	if t.After(start) {
		d = t.Sub(start)
	}
	fb.Fields = append(fb.Fields, Field{Key: key, Value: d})
	return fb.Self
}

// Uint adds a uint field.
func (fb *FieldBuilder[T]) Uint(key string, val uint) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Uint8 adds a uint8 field.
func (fb *FieldBuilder[T]) Uint8(key string, val uint8) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Uint16 adds a uint16 field.
func (fb *FieldBuilder[T]) Uint16(key string, val uint16) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Uint32 adds a uint32 field.
func (fb *FieldBuilder[T]) Uint32(key string, val uint32) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Uint64 adds a uint64 field.
func (fb *FieldBuilder[T]) Uint64(key string, val uint64) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: val})
	return fb.Self
}

// Uints adds a uint slice field.
func (fb *FieldBuilder[T]) Uints(key string, vals []uint) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Uints8 adds a uint8 slice field.
func (fb *FieldBuilder[T]) Uints8(key string, vals []uint8) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Uints16 adds a uint16 slice field.
func (fb *FieldBuilder[T]) Uints16(key string, vals []uint16) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Uints32 adds a uint32 slice field.
func (fb *FieldBuilder[T]) Uints32(key string, vals []uint32) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}

// Uints64 adds a uint64 slice field.
func (fb *FieldBuilder[T]) Uints64(key string, vals []uint64) *T {
	fb.Fields = append(fb.Fields, Field{Key: key, Value: vals})
	return fb.Self
}
