// Code generated by "stringer -type=NumberFormat -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NumberPlain-0]
	_ = x[NumberGrouped-1]
	_ = x[NumberCompact-2]
}

const _NumberFormat_name = "plaingroupedcompact"

var _NumberFormat_index = [...]uint8{0, 5, 12, 19}

func (i NumberFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NumberFormat_index)-1 {
		return "NumberFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NumberFormat_name[_NumberFormat_index[idx]:_NumberFormat_index[idx+1]]
}
