name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: {}

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
    uses: gechr/actions/.github/workflows/release-notes.yaml@f86637c131004611b2346f2f3102ed291b13a412 # v0.2.9
